name: Main

on:
  push:
    branches: [main]

env:
  DOCKER_USER: ${{ github.actor }}
  PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
  REPO_OWNER: ${{ github.repository_owner }}
  SSH_HOST: ${{ secrets.VPS_SSH_HOST }}
  SSH_IP: ${{ secrets.VPS_SSH_IP }}
  SSH_USER: ${{ secrets.VPS_SSH_USER }}
  SSH_PASSWORD: ${{ secrets.VPS_SSH_PASSWORD }}
  SSH_PORT: ${{ secrets.VPS_SSH_PORT }}

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      web: ${{ steps.filter.outputs.web }}
      api: ${{ steps.filter.outputs.api }}
      lib: ${{ steps.filter.outputs.lib }}
    steps:
      - uses: actions/checkout@v4
      # Filter paths per package to only deploy changed packages
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            web:
              - 'web/**'
            api:
              - 'api/**'
            lib:
              - 'lib/**'

  build-and-deploy-web:
    needs: detect
    if: needs.detect.outputs.web == 'true' || needs.detect.outputs.lib == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build web
        run : docker build . -t tanzia-web -f ./web/Dockerfile
      - name: Push docker image
        run: |
          docker login ghcr.io -u $GITHUB_ACTOR -p $PAT_TOKEN
          docker tag tanzia-web ghcr.io/$REPO_OWNER/tanzia-web:latest
          docker push ghcr.io/$REPO_OWNER/tanzia-web:latest
      - name: Rollout new version
        run: sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_IP -p $SSH_PORT 'sudo kubectl rollout restart deployment tanzia-web'

  build-and-deploy-api:
    needs: detect
    if: needs.detect.outputs.api == 'true' || needs.detect.outputs.lib == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build api
        run: docker build . -t tanzia-api -f ./api/Dockerfile
      - name: Push docker image
        run: |
          docker login ghcr.io -u $GITHUB_ACTOR -p $PAT_TOKEN
          docker tag tanzia-api ghcr.io/$REPO_OWNER/tanzia-api:latest
          docker push ghcr.io/$REPO_OWNER/tanzia-api:latest
      - name: Rollout new version
        run: sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_IP -p $SSH_PORT 'sudo kubectl rollout restart deployment tanzia-api'
