FROM golang:alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY web web
RUN apk add gcc musl-dev
RUN CGO_ENABLED=1 go build -o /app/tanzia-web ./web/...

FROM golang:alpine

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY --from=builder /app/tanzia-web /app/tanzia-web

CMD ["air", "-c", "/app/air.toml"]
